// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDevkMgu27IH5qXYF2oqYKmSo5AX1NvRTM',
    appId: '1:1024198714807:web:834b550b7266062605b432',
    messagingSenderId: '1024198714807',
    projectId: 'valorant0471',
    authDomain: 'valorant0471.firebaseapp.com',
    storageBucket: 'valorant0471.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5lMqPLnW1uQLCeLKRuP1LwFxq--XeBqU',
    appId: '1:1024198714807:android:10377b2279fe0a6805b432',
    messagingSenderId: '1024198714807',
    projectId: 'valorant0471',
    storageBucket: 'valorant0471.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3IvcyJ_gviu1e1PaYLrWTTZVDwf0X9ko',
    appId: '1:1024198714807:ios:ad9ed54b4b14905405b432',
    messagingSenderId: '1024198714807',
    projectId: 'valorant0471',
    storageBucket: 'valorant0471.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3IvcyJ_gviu1e1PaYLrWTTZVDwf0X9ko',
    appId: '1:1024198714807:ios:ad9ed54b4b14905405b432',
    messagingSenderId: '1024198714807',
    projectId: 'valorant0471',
    storageBucket: 'valorant0471.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDevkMgu27IH5qXYF2oqYKmSo5AX1NvRTM',
    appId: '1:1024198714807:web:ed056ca9b2b92cf105b432',
    messagingSenderId: '1024198714807',
    projectId: 'valorant0471',
    authDomain: 'valorant0471.firebaseapp.com',
    storageBucket: 'valorant0471.firebasestorage.app',
  );
}
